### ISSUE TITLE
Adoption/Maintenance offer

### ISSUE THREAD

**Issue by pburkholder** [mdxp/knife-cleanup#7]
Hi Marius,

Looks like this plugin still has a fair amount of interest, would you like some help maintaining it? I'd be happy to curate the pending PRs and tend to issues if you could provide me the commit bit.

Cheers,

Peter

**Comment by mdxp** [comment]
Thank you so much for your offer Peter. Would love to have you help out. I will add you with full access to the repo.

Thanks,
- Marius -

**Comment by mdxp** [comment]
Done!
