### ISSUE TITLE
Unable to resolve dependencies

### ISSUE THREAD

**Issue by adrianmoisey** [mdxp/knife-cleanup#9]
I get the following error when trying to install `knife-cleanup`:

```
ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: chef requires chef-config (= 12.4.1); ohai requires chef-config (< 13, >= 12.5.0.alpha.1)
```

**Comment by pmoosh** [comment]
@adrianmoisey I assume you are running:
chef gem install.

I just ran that and it worked fine - I am using chefDk 0.7.0
chef --version
Chef Development Kit Version: 0.7.0
chef-client version: 12.4.1
berks version: 3.2.4
kitchen version: 1.4.2
May you can show us your chef gem list output

**Comment by adrianmoisey** [comment]
> @adrianmoisey I assume you are running:
> chef gem install.

Hah! I wasn't. My bad.

All sorted now, thanks for the help :)
